#pragma once
enum class DynamicObjectType {
	_0 = 0,
	FIRE = 1,
	FISH, // 2
	FISHOBJECT,// 3
	MINERAL1,// 4
	MINERAL2,// 5
	ARESDENFLAG1,// 6
	ELVINEFLAG1,// 7
	ICESTORM,// 8
	SPIKE,// 9
	PCLOUD_BEGIN,// 10
	PCLOUD_LOOP,// 11
	PCLOUD_END,// 12
	FIRE2,// 13
	FIRE3// 14
};
/*
#define DEF_DYNAMICOBJECT_FIRE			1
#define DEF_DYNAMICOBJECT_FISH			2
#define DEF_DYNAMICOBJECT_FISHOBJECT	3
#define DEF_DYNAMICOBJECT_MINERAL1		4
#define DEF_DYNAMICOBJECT_MINERAL2		5
#define DEF_DYNAMICOBJECT_ARESDENFLAG1	6
#define DEF_DYNAMICOBJECT_ELVINEFLAG1	7
#define DEF_DYNAMICOBJECT_ICESTORM		8
#define DEF_DYNAMICOBJECT_SPIKE			9
#define DEF_DYNAMICOBJECT_PCLOUD_BEGIN	10
#define DEF_DYNAMICOBJECT_PCLOUD_LOOP	11
#define DEF_DYNAMICOBJECT_PCLOUD_END	12
#define DEF_DYNAMICOBJECT_FIRE2			13
#define DEF_DYNAMICOBJECT_FIRE3			14
*/